--scripts to create tables for spring-hibernate operations

CREATE TABLE CONTACT_SPHB (
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1
, FIRST_NAME VARCHAR(60) NOT NULL
, LAST_NAME VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION NUMBER DEFAULT ON NULL 0
, CONSTRAINT UQ_CONTACT_1 UNIQUE (FIRST_NAME, LAST_NAME)
, PRIMARY KEY (ID)
);

CREATE TABLE HOBBY_SPHB (
HOBBY_ID VARCHAR(20) NOT NULL
, PRIMARY KEY (HOBBY_ID)
);

CREATE TABLE CONTACT_TEL_DETAIL_SPHB (
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1
, CONTACT_ID INT NOT NULL
, TEL_TYPE VARCHAR(20) NOT NULL
, TEL_NUMBER VARCHAR(20) NOT NULL
, VERSION NUMBER DEFAULT ON NULL 0
, CONSTRAINT UQ_CONTACT_TEL_DETAIL_1 UNIQUE (CONTACT_ID, TEL_TYPE)
, PRIMARY KEY (ID)
, CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY (CONTACT_ID)
REFERENCES CONTACT_SPHB (ID)
);

CREATE TABLE CONTACT_HOBBY_DETAIL_SPHB (
CONTACT_ID NUMBER NOT NULL
, HOBBY_ID VARCHAR(20) NOT NULL
, PRIMARY KEY (CONTACT_ID, HOBBY_ID)
, CONSTRAINT FK_CONTACT_HOBBY_DETAIL_1 FOREIGN KEY (CONTACT_ID)
REFERENCES CONTACT_SPHB (ID) ON DELETE CASCADE
, CONSTRAINT FK_CONTACT_HOBBY_DETAIL_2 FOREIGN KEY (HOBBY_ID)
REFERENCES HOBBY_SPHB (HOBBY_ID)
);

--scripts to insert dummy data into tables
insert into contact_sphb (first_name, last_name, birth_date) values ('Chris', 'Schaefer', TO_DATE('1981-05-03','yyyy-mm-dd'));
insert into contact_sphb (first_name, last_name, birth_date) values ('Scott', 'Tiger', TO_DATE('1990-11-02','yyyy-mm-dd'));
insert into contact_sphb (first_name, last_name, birth_date) values ('John', 'Smith', TO_DATE('1964-02-28','yyyy-mm-dd'));
insert into contact_tel_detail_sphb (contact_id, tel_type, tel_number) values (1, 'Mobile', '1234567890');
insert into contact_tel_detail_sphb (contact_id, tel_type, tel_number) values (1, 'Home', '1234567890');
insert into contact_tel_detail_sphb (contact_id, tel_type, tel_number) values (2, 'Home', '1234567890');
insert into hobby_sphb (hobby_id) values ('Swimming');
insert into hobby_sphb (hobby_id) values ('Jogging');
insert into hobby_sphb (hobby_id) values ('Programming');
insert into hobby_sphb (hobby_id) values ('Movies');
insert into hobby_sphb (hobby_id) values ('Reading');
insert into contact_hobby_detail_sphb (contact_id, hobby_id) values (1, 'Swimming');
insert into contact_hobby_detail_sphb (contact_id, hobby_id) values (1, 'Movies');
insert into contact_hobby_detail_sphb (contact_id, hobby_id) values (2, 'Swimming');